### ISSUE TITLE
Issues with Grid Cascading Combos sample

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-wc-examples#864]
1) when run from online samples (https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/cascading-combos) an error is thrown in the console 
Uncaught Error: Error on fetching sample files!
    at t.sampleFilesFetchErrorHandler (main.20558c30825c55ce5c13.js:1:32991)
    at Object.error (main.20558c30825c55ce5c13.js:1:32154)
    at fire (jquery-3.1.0.js:3243:31)
    at Object.fireWith [as rejectWith] (jquery-3.1.0.js:3373:7)
    at done (jquery-3.1.0.js:9100:14)
    at XMLHttpRequest.<anonymous> (jquery-3.1.0.js:9340:9)

2) when built from samples source (seen in vnext branch) and run, if you select an item from the first combo, when you try and select an item from the first combo an error is received: 
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:8080/f8b58105e030fc6a931c.bundle.js:79533:58)
    at http://localhost:8080/f8b58105e030fc6a931c.bundle.js:79552:7

**Comment by MarielaTihova** [comment]
1. Resolved with the PR linked to this issue (https://github.com/IgniteUI/igniteui-xplat-docs/pull/1436)
2. Happens only in dev mode
